mollie_payment:
    resource:     "@MolliePaymentBundle/Controller/AjaxMollieController.php"
    type:         annotation
    prefix:       /mollie

mollie_support:
    resource:     "@MolliePaymentBundle/Controller/SupportController.php"
    type:         annotation
    prefix:       /mollie

mollie_payment_link:
    resource:     "@MolliePaymentBundle/Controller/PaymentLinkController.php"
    type:         annotation
    prefix:       /mollie
    options:
        frontend: true

mollie_active_payment_methods:
    resource:     "@MolliePaymentBundle/Controller/ActivePaymentMethodsController.php"
    type:         annotation
    prefix:       /mollie

mollie_payment_callback:
    resource: "@MolliePaymentBundle/Controller/CallbackController.php"
    type: annotation
    prefix: /payment/callback
    options:
        frontend: true
